development:
  clients:
    default:
      database: adcustomera_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: adcustomera_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: adcustomera_production
      hosts:
        - 127.0.0.1:27017
      options:
        server_selection_timeout: 5

